alias d='docker'
alias dc='docker-compose'
alias k='kubectl'
alias ki='kubectl --insecure-skip-tls-verify'
# alias kpa='kubectl get po -A -o custom-columns=NAMESPACE:metadata.namespace,NAME:metadata.name,STATUS:status.phase,NODE:spec.nodeName -w'
alias tf='terraform'
alias ll='logo-ls -lah'
# alias loadnvm='. /usr/local/opt/nvm/nvm.sh'
# alias pw='pwgen -sync 128 1'
alias awsi='aws --no-verify-ssl'
alias dbuild='docker build --build-arg http_proxy="$http_proxy" --build-arg https_proxy="$https_proxy" --build-arg no_proxy="$no_proxy" -t'
alias t='traceroute -I -q 1 -w 1'
